version: '3.7'

services:
  gooddata-cn-ce:
    image: gooddata/gooddata-cn-ce:dev_latest
    ports:
      - "3000:3000"
      - "5432:5432"
    volumes:
      - gooddata-cn-ce-data:/data
    environment:
      LICENSE_AND_PRIVACY_POLICY_ACCEPTED: "YES"
      BUNDLE_TYPE: "gdc"

  gooddata-mm-demo-bootstrap:
    build:
      context: ./
      dockerfile: Dockerfile_gooddata_bootstrap
    tty: true
    depends_on:
      - gooddata-cn-ce
    environment:
      TIGER_ENDPOINT: "http://gooddata-cn-ce:3000"
      TIGER_API_TOKEN: "YWRtaW46Ym9vdHN0cmFwOmFkbWluMTIz"
      OVERRIDE_HOST: "localhost"
      DB_HOST: "gooddata-cn-ce"
      DB_USER: "demouser"
      DB_PASSWORD: "demopass"
      DB_NAME: "demo"
      DB_INPUT_SCHEMA: "faa_input"
      DB_OUTPUT_SCHEMA: "faa"
    entrypoint:
      - bash
      - -c
      - "cd gooddata && ./bootstrap.sh"

volumes:
  gooddata-cn-ce-data:
