version: 2

models:
  - name: flights
    columns:
      - name: id2
        tests:
          - dbt_constraints.primary_key
      - name: carrier
        tests:
          - dbt_constraints.foreign_key:
              pk_table_name: ref('carriers')
              pk_column_name: code
      - name: origin
        tests:
          - dbt_constraints.foreign_key:
              pk_table_name: ref('airports')
              pk_column_name: code
      # destination is skipped, GoodData cannot utilize it to generate two roles of airports
      - name: tail_num
        tests:
          - dbt_constraints.foreign_key:
              pk_table_name: ref('aircraft')
              pk_column_name: tail_num
