create table "aircraft"(
  "id" int,
  "tail_num" varchar,
  "aircraft_serial" varchar,
  "aircraft_model_code" varchar,
  "aircraft_engine_code" varchar,
  "year_built" int,
  "aircraft_type_id" int,
  "aircraft_engine_type_id" int,
  "registrant_type_id" int,
  "name" varchar,
  "address1" varchar,
  "address2" varchar,
  "city" varchar,
  "state" varchar,
  "zip" varchar,
  "region" varchar,
  "county" varchar,
  "country" varchar,
  "certification" varchar,
  "status_code" varchar,
  "mode_s_code" varchar,
  "fract_owner" varchar,
  "last_action_date" date,
  "cert_issue_date" date,
  "air_worth_date" date,
  constraint "pk_aircraft" primary key ("tail_num"),
  constraint "fk_aircraft_aircraft_models" foreign key ("aircraft_model_code") references "aircraft_models"("aircraft_model_code")
);
