create table "airports"(
   "id" int,
   "code" varchar,
   "site_number" varchar,
   "fac_type" varchar,
   "fac_use" varchar,
   "faa_region" varchar,
   "faa_dist" varchar,
   "city" varchar,
   "county" varchar,
   "state" varchar,
   "full_name" varchar,
   "own_type" varchar,
   "longitude" float,
   "latitude" float,
   "elevation" int,
   "aero_cht" varchar,
   "cbd_dist" int,
   "cbd_dir" varchar,
   "act_date" varchar,
   "cert" varchar,
   "fed_agree" varchar,
   "cust_intl" varchar,
   "c_ldg_rts" varchar,
   "joint_use" varchar,
   "mil_rts" varchar,
   "cntl_twr" varchar,
   "major" varchar,
   constraint "pk_airports" primary key ("code")
);
